### ISSUE TITLE
Postgresql password not being properly output in the DSN

### ISSUE THREAD

**Issue by mcfearsome** [paralus/helm-charts#44]
### Expected vs actual behavior

I expect the DSN in secrets to include the configured password.
-
`<no value>` is output where the password should be.

### Steps to reproduce the bug

1. disable the embedded postgresql install `.Values.deploy.postgresql.enable=false`
2. configure the required postgresql variables for building the DSN 
3. run `helm template .` and inspect the `paralus-db` secret.

### Are you using the latest version of the project?

```
  chart:
    spec:
      chart: ztka
      version: "~> 0.1.0"
      sourceRef:
        kind: HelmRepository
        name: paralus
```

-

### Notes

Will open a PR fixing this issue but it also contains other changes to allow the explicit setting of the postgresql DSN

- [x] I've described the bug, included steps to reproduce it, and included my environment setup with all customizations.
- [x] I'm using the latest version of the project.
